_wandb:
    value:
        cli_version: 0.21.2
        e:
            n3dc1vpkz12409cfkd91033bbq1w68mt:
                codePath: OneDrive\Desktop\AI Project 2025\DQN based\dqn1.py
                codePathLocal: dqn1.py
                cpu_count: 12
                cpu_count_logical: 16
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "510744588288"
                        used: "444254302208"
                email: mehul22@iisertvm.ac.in
                executable: C:\Users\mehul\anaconda3\envs\clean\python.exe
                git:
                    commit: bac88fb19078075aed634a656e697449bf6e01a8
                    remote: https://github.com/Mehul1729/PINN-for-Damped-Oscillation.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-96ef0870-1a5f-024b-b3dd-89750af5ad91
                host: LAPTOP-EIU04378
                memory:
                    total: "16870006784"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\mehul\OneDrive\Desktop\AI Project 2025\DQN based\dqn1.py
                python: CPython 3.11.11
                root: C:\Users\mehul\OneDrive\Desktop\AI Project 2025\DQN based
                startedAt: "2025-10-30T18:58:04.476775Z"
                writerId: n3dc1vpkz12409cfkd91033bbq1w68mt
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
            "4": 3.11.11
            "5": 0.21.2
            "8":
                - 3
            "12": 0.21.2
            "13": windows-amd64
architecture:
    value: DQN_64x64
batch_size:
    value: 128
environment:
    value: Extreme-8-Deck
episodes:
    value: 3000
gamma:
    value: 0.9
learning_rate:
    value: 0.001
